### ISSUE TITLE
Problem with strftime while getting transactions ING

### ISSUE THREAD

**Issue by cgarciabarrera** [ismaGNU/bank_scrap#16]
When executing from command line, there is a problem with something refered to a date.

Here my console response.
Running on Mac OS X Yosemite.

bank_scrap transactions ing --user 00000000R --password XXXXXX --extra=birthday:05/01/19XX

Transactions for: Cuenta NÓMINA nombredelacuenta (ES24 1465 0100 XX XXXXXXXXXX)
/Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/bank_scrap-0.0.8/lib/bank_scrap/transaction.rb:14:in `to_s': undefined method `strftime' for "05/02/2015":String (NoMethodError)
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/bank_scrap-0.0.8/lib/bank_scrap/cli.rb:40:in `block in transactions'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/bank_scrap-0.0.8/lib/bank_scrap/cli.rb:39:in `each'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/bank_scrap-0.0.8/lib/bank_scrap/cli.rb:39:in `transactions'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/gems/bank_scrap-0.0.8/bin/bank_scrap:5:in `<top (required)>'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/bin/bank_scrap:23:in `load'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/bin/bank_scrap:23:in `<main>'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/fulanitodetal/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

Hope you find that bug.

Thanks

**Comment by javiercr** [comment]
@cgarciabarrera I see you're using version `0.0.8`, could you try updating to the latest version (`0.0.10`)? I think that's is fixed in the last version.

Thanks!

**Comment by cgarciabarrera** [comment]
Perfect. Now works like a charm.

Thanks
