### ISSUE TITLE
Let's switch to another HTTP library

### ISSUE THREAD

**Issue by javiercr** [ismaGNU/bank_scrap#9]
Right now we are using [curb](https://github.com/taf2/curb) to perform all HTTP requests. It's a simple wrapper around curl.

The thing is that I found a weird behavior that doesn't allow me to implement transactions fetching for BBVA. I've opened [an issue](https://github.com/taf2/curb/issues/224) in curb's repository but it seems the project is not actively maintained. 

There are [55 open issues](https://github.com/taf2/curb/issues) in curb, most of them without any response from the project's maintainers, so I would like to propose switching to a different HTTP library.

In the initial BBVA gem I was using [faraday](https://github.com/lostisland/faraday), but to add cookies support I had to use [faraday-cookie_jar](https://github.com/miyagawa/faraday-cookie_jar) and the code was perhaps too complex.

I'd suggest either [rest-client](https://github.com/rest-client/rest-client) or [httparty](https://github.com/jnunemaker/httparty).

What do you think? @raulmarcosl @ismaGNU @ferblape

**Comment by taf2** [comment]
fyi curb 's not abandon'ed what issue were you having?
